Repository wecode-bootcamp-korea/42-2nd-HomeAlone-frontend, pull requests merged in 2023-03, with the labels that each got.

#6 [42기 이종혁] HomeWarming 레이아웃
  public/images/HomeWarming/bookmark.png
  public/images/HomeWarming/comment.png
  public/images/HomeWarming/haert.png
  public/images/HomeWarming/room.jpg
  public/images/HomeWarming/userImg.png
  src/pages/HomeWarming/Comment/Comment.Style.jsx
  src/pages/HomeWarming/Comment/Comment.jsx
  src/pages/HomeWarming/HomeWarming.Style.jsx
  src/pages/HomeWarming/HomeWarming.js
  src/pages/HomeWarming/HomeWarming.jsx
  src/pages/HomeWarming/SideBar/SideBar.Style.jsx
  src/pages/HomeWarming/SideBar/SideBar.jsx
Labels: 완료

#14 [42기 성은정] payment 레이아웃
  package-lock.json
  package.json
  public/data/carts.json
  public/data/users.json
  public/images/payment/card.png
  public/images/payment/deposit.png
  public/images/payment/kakao.png
  public/images/payment/naver.png
  public/images/payment/payco.png
  public/images/payment/phone.png
  public/images/payment/toss.png
  src/pages/Payment/Payment.js
  src/pages/Payment/Payment.jsx
  src/pages/Payment/Payment.style.jsx
  src/pages/Payment/components/AddressBox/AddressBox.jsx
  src/pages/Payment/components/AddressBox/AddressBox.style.jsx
  src/pages/Payment/components/CartItem/CartItem.jsx
  src/pages/Payment/components/CartItem/CartItem.style.jsx
  src/pages/Payment/components/PaymentOptions/PaymentOptions.jsx
  src/pages/Payment/components/PaymentOptions/PaymentOptions.style.jsx
  src/pages/Payment/components/Sidebar/Sidebar.jsx
  src/pages/Payment/components/Sidebar/Sidebar.style.jsx
  src/pages/Payment/components/UserBox/UserBox.jsx
  src/pages/Payment/components/UserBox/UserBox.style.jsx
  src/pages/Payment/data/paymentOptions.js
Labels: 수정 요청

#15 [42기 성은정] mixin 내용 추가
  src/styles/mixin.js
Labels: 완료

#5 [42기 이종혁] home warming list 레이아웃
  public/data/HomeWarmingLIst.json
  public/images/HomeWarmingList/down-arrow.png
  public/images/HomeWarmingList/room.jpg
  public/images/HomeWarmingList/userImg.png
  src/Router.js
  src/pages/HomeWarmingList/Filter/Filter.Style.jsx
  src/pages/HomeWarmingList/Filter/Filter.jsx
  src/pages/HomeWarmingList/Filter/FilterModal.Style.jsx
  src/pages/HomeWarmingList/Filter/FilterModal.jsx
  src/pages/HomeWarmingList/HomeWarmingList.Style.jsx
  src/pages/HomeWarmingList/HomeWarmingList.js
  src/pages/HomeWarmingList/HomeWarmingList.jsx
  src/pages/HomeWarmingList/List.Style.jsx
  src/pages/HomeWarmingList/List.jsx
Labels: 완료

#11 [42기 성은정] main 레이아웃
  public/data/posts.json
  public/images/main/lovely1.jpg
  public/images/main/lovely2.jpg
  public/images/main/mainRoom.jpg
  public/images/main/modern1.jpg
  public/images/main/modern2.jpg
  public/images/main/vintage1.jpg
  public/images/main/vintage2.jpg
  src/pages/Main/Main.js
  src/pages/Main/Main.jsx
  src/pages/Main/Main.style.jsx
Labels: 완료

#13 [42기 이수민] Add: collections 레이아웃 기능 구현 완료
  public/data/houseWarming.json
  public/images/soomin/houseWarming1.jpg
  public/images/soomin/houseWarming2.jpg
  public/images/soomin/houseWarming3.jpg
  public/images/soomin/houseWarming4.jpg
  public/images/soomin/houseWarming5.jpg
  src/pages/Collections/Collections.js
  src/pages/Collections/Collections.jsx
  src/pages/Collections/Collections.style.jsx
Labels: 완료

#16 [42기 이수민] Add : Collections API 연결
  public/data/houseWarmingList.json
  src/pages/Collections/Collections.jsx
Labels: 완료

#19 [42기 성은정] nav 기능
  src/Hooks/useSearch.js
  src/components/Nav/Nav.style.jsx
  src/components/Nav/components/Search/Search.jsx
  src/components/Nav/components/SearchBox/SearchBox.jsx
  src/components/Nav/components/SearchBox/SearchBox.style.jsx
Labels: 완료

#20 [42기 성은정] footer 레이아웃 수정
  src/components/Footer/Footer.jsx
  src/components/Footer/Footer.style.jsx
Labels: 완료

#18 [42기 성은정] main 기능
  package-lock.json
  package.json
  src/pages/Main/Main.jsx
  src/pages/Main/Main.style.jsx
  src/styles/mixin.js
Labels: 멘토 리뷰 요청

#21 [42기 이수민] Add : 공용 API 관리 파일 생성
  src/Router.js
  src/config/config.js
Labels: 완료

#12 [42기 이수민] Modify: 카카오 로그인 API 구현
  .gitignore
  package-lock.json
  package.json
  public/images/soomin/withkakao.png
  src/Router.js
  src/config/config.js
  src/pages/Login/KakaoRedirect.jsx
  src/pages/Login/Login.jsx
  src/pages/Login/Login.style.jsx
  src/pages/Login/components/LoadingSpinner.jsx
  src/pages/Login/components/LoadingSpninner.style.jsx
Labels: 완료

#17 [42기 성은정] posting 레이아웃
  public/data/products.json
  public/images/posting/logo.png
  public/images/posting/photo.png
  src/Hooks/usePost.js
  src/Hooks/useSearch.js
  src/config/config.js
  src/pages/Posting/Posting.js
  src/pages/Posting/Posting.jsx
  src/pages/Posting/Posting.style.jsx
  src/pages/Posting/components/ContentForm/ContentForm.jsx
  src/pages/Posting/components/ContentForm/ContentForm.style.jsx
  src/pages/Posting/components/MarkerModal/MarkerModal.jsx
  src/pages/Posting/components/MarkerModal/MarkerModal.style.jsx
Labels: 완료

#28 [42기 이수민] collections config.js로 API 연결
  src/config/config.js
  src/pages/Collections/Collections.jsx
  src/pages/Collections/Collections.style.jsx
Labels: Conflict 해결 요청, 멘토 리뷰 요청

#26 [42기 성은정] posting 기능
  src/pages/Posting/components/ContentForm/ContentForm.jsx
  src/pages/Posting/components/ContentForm/ContentForm.style.jsx
  src/pages/Posting/components/MarkerModal/MarkerModal.jsx
  src/pages/Posting/components/MarkerModal/MarkerModal.style.jsx
Labels: 완료

#9 [42기 이수민] 🔨Add: 장바구니 레이아웃 구현
  public/data/cartList.json
  public/images/soomin/cart.png
  src/config/config.js
  src/pages/Cart/Cart.js
  src/pages/Cart/Cart.jsx
  src/pages/Cart/Cart.style.jsx
  src/pages/Cart/components/CartItem/CartItem.jsx
  src/pages/Cart/components/CartItem/CartItem.style.jsx
  src/pages/Cart/components/TotalPrice/TotalPrice.jsx
  src/pages/Cart/components/TotalPrice/TotalPrice.style.jsx
  src/styles/GlobalStyle.js
Labels: 완료

#30 [42기 성은정] nav 기능 수정
  src/Hooks/useSearch.js
  src/components/Nav/Nav.jsx
  src/components/Nav/Nav.style.jsx
  src/components/Nav/components/Search/Search.jsx
  src/components/Nav/components/Search/Search.style.jsx
  src/components/Nav/components/SearchBox/SearchBox.jsx
  src/components/Nav/components/SearchBox/SearchBox.style.jsx
  src/config/config.js
Labels: 멘토 리뷰 요청

#32 [42기 이종혁] homewarminglist page 필터링기능, 페이지네이션 구현"
  public/data/HomeWarmingLIst.json
  src/config/config.js
  src/pages/HomeWarmingList/Filter/Filter.jsx
  src/pages/HomeWarmingList/Filter/FilterModal.jsx
  src/pages/HomeWarmingList/HomeWarmingList.jsx
  src/pages/HomeWarmingList/List.jsx
  src/pages/HomeWarmingList/List/List.Style.jsx
  src/pages/HomeWarmingList/List/List.jsx
Labels: 멘토 리뷰 요청

#34 [42기 이수민] hotFix
  src/components/Nav/Nav.jsx
  src/config/config.js
  src/pages/Cart/components/CartItem/CartItem.jsx
  src/pages/Collections/Collections.jsx
  src/pages/Collections/Collections.style.jsx
  src/pages/Detail/Detail.jsx
  src/pages/Detail/ProductInfo/ProductInfo.jsx
  src/pages/Detail/Review/Review.jsx
  src/pages/HomeWarming/Comment/Comment.jsx
  src/pages/HomeWarming/HomeWarming.Style.jsx
  src/pages/HomeWarming/HomeWarming.jsx
  src/pages/HomeWarming/SideBar/SideBar.jsx
  src/pages/Main/Main.jsx
  src/pages/Main/Main.style.jsx
  src/pages/Payment/Payment.jsx
  src/pages/Payment/components/UserBox/UserBox.jsx
  src/pages/Posting/Posting.jsx
Labels: 멘토 리뷰 요청

#33 [42기 성은정] main 캐러셀 수정
  src/config/config.js
  src/pages/Main/Main.jsx
Labels: Conflict 해결 요청
